# [START cloudbuild]
steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'eu.gcr.io/k8s-16244410/k8s-demo-app:$BUILD_ID'
  - '-t'
  - 'eu.gcr.io/k8s-16244410/k8s-demo-app:latest'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Build-2
  args:
  - 'build'
  - '-t'
  - 'gcr.io/k8s-16244410/k8s-demo-app:$BUILD_ID'
  - '-t'
  - 'gcr.io/k8s-16244410/k8s-demo-app:latest'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'eu.gcr.io/k8s-16244410/k8s-demo-app'

- name: 'gcr.io/cloud-builders/docker'
  id: Push-2
  args:
  - 'push'
  - 'gcr.io/k8s-16244410/k8s-demo-app'

# [END cloudbuild]