apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: eu.gcr.io/tto-demo/k8s_demo-app
    sync:
      infer:
      - 'website/*.html'
deploy:
  kubectl:
    manifests:
    - config/deployment.yml
portForward:
- resourceType: deployment
  resourceName: dpl-demo
  namespace: default
  port: 80
  localPort: 9000 # *Optional*