apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-1
  name: deployment-demo-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-1
    spec:
      containers:
      - image: eu.gcr.io/container-registry-301121/demo_website:v1
        name: demo-container
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst